/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        cadence: {
          50: '#eef0ff',
          100: '#dfe2ff',
          200: '#c6caff',
          300: '#a5b4fc',
          400: '#7c85e8',
          500: '#5558c8',
          600: '#3d4280',
          700: '#3d4280',
          800: '#2d3161',
          900: '#1e2147',
          950: '#0d0f1f',
        },
        copper: {
          300: '#eac9a8',
          400: '#e0b08a',
          500: '#d4956b',
          600: '#c07a4e',
          700: '#a66339',
        },
        bubblegum: {
          cream:       '#fff7e0',
          'cream-hi':  '#fffdf3',
          butter:      '#ffd66b',
          peach:       '#ffaf95',
          mint:        '#a8e6b8',
          sky:         '#a8d8ff',
          lavender:    '#cfb6ff',
          pink:        '#ffb3d9',
          cherry:      '#ff7faf',
          plum:        '#3a224f',
          'plum-soft': '#6b4a85',
          'plum-dim':  '#9d85b6',
          green:       '#27a059',
          rose:        '#e84d6f',
        },
        night: {
          ink:        '#180e23',
          panel:      '#261735',
          panel2:     '#34234a',
          'panel-hi': '#3d2b58',
          fg:         '#fff7e0',
          fg2:        '#d8c8e8',
          fg3:        '#a191b0',
          'fg-dim':   '#6e5e80',
        },
      },
      borderRadius: {
        bubble: '32px',
      },
      backgroundImage: {
        'bubble-pattern': `radial-gradient(circle at 12% 18%, rgba(255,175,149,0.33) 0 8px, transparent 9px),
                           radial-gradient(circle at 78% 8%, rgba(168,230,184,0.33) 0 10px, transparent 11px),
                           radial-gradient(circle at 90% 70%, rgba(207,182,255,0.33) 0 12px, transparent 13px),
                           radial-gradient(circle at 6% 80%, rgba(168,216,255,0.33) 0 8px, transparent 9px),
                           radial-gradient(circle at 50% 40%, rgba(255,214,107,0.2) 0 6px, transparent 7px)`,
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      animation: {
        'bounce-in': 'bounceIn 0.4s cubic-bezier(0.36, 0.07, 0.19, 0.97)',
        'shake': 'shake 0.4s cubic-bezier(0.36, 0.07, 0.19, 0.97)',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'pulse-xp': 'pulseXP 0.6s ease-out',
        'bg-pop-in':      'bg-pop-in .5s cubic-bezier(.36,.07,.19,.97) both',
        'bg-rise':        'bg-rise .45s cubic-bezier(.36,.07,.19,.97) both',
        'bg-tick':        'bg-tick .35s cubic-bezier(.36,.07,.19,.97) both',
        'bg-shake':       'bg-shake .5s cubic-bezier(.36,.07,.19,.97)',
        'bg-streak-glow': 'bg-streak-glow 1.6s ease-in-out infinite',
        'bg-float-up':    'bg-float-up 1.2s cubic-bezier(.36,.07,.19,.97) forwards',
      },
      keyframes: {
        bounceIn: {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '60%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        pulseXP: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.3)', color: '#F59E0B' },
          '100%': { transform: 'scale(1)' },
        },
        'bg-pop-in': {
          '0%':   { opacity: '0', transform: 'scale(.6) rotate(-12deg)' },
          '55%':  { opacity: '1', transform: 'scale(1.15) rotate(-3deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(-3deg)' },
        },
        'bg-rise': {
          '0%':   { opacity: '0', transform: 'translateY(60px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'bg-tick': {
          '0%':   { transform: 'scale(0) rotate(-30deg)' },
          '60%':  { transform: 'scale(1.3) rotate(8deg)' },
          '100%': { transform: 'scale(1) rotate(0deg)' },
        },
        'bg-shake': {
          '0%, 100%':      { transform: 'translateX(0)' },
          '10%, 50%, 90%': { transform: 'translateX(-8px)' },
          '30%, 70%':      { transform: 'translateX(8px)' },
        },
        'bg-streak-glow': {
          '0%, 100%': { transform: 'scale(1) rotate(-8deg)', filter: 'drop-shadow(0 0 0 rgba(255,175,149,0))' },
          '50%':      { transform: 'scale(1.15) rotate(-8deg)', filter: 'drop-shadow(0 0 10px rgba(255,175,149,0.75))' },
        },
        'bg-float-up': {
          '0%':   { opacity: '0', transform: 'translateY(8px) rotate(-3deg)' },
          '20%':  { opacity: '1', transform: 'translateY(-4px) rotate(-3deg)' },
          '80%':  { opacity: '1', transform: 'translateY(-40px) rotate(-3deg)' },
          '100%': { opacity: '0', transform: 'translateY(-60px) rotate(-3deg)' },
        },
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
      },
    },
  },
  plugins: [],
}
